#!/usr/bin/env julia

using JSON3
using Printf
using Dates

const CAMPAIGN_MAP = [
    ("CASES-99", "cases_99", "CASES"),
    ("GABLS3", "gabls3", "GABLSthree"),
    ("FLOSS", "floss", "FLOSS"),
    ("BLLAST", "bllast", "BLLAST"),
]

function read_json(path::String)
    isfile(path) || return nothing
    return JSON3.read(read(path, String))
end

function fmt_num(x; digits::Int=4)
    if x === nothing
        return "n/a"
    end
    v = try
        Float64(x)
    catch
        return "n/a"
    end
    if !isfinite(v)
        return "n/a"
    end
    return @sprintf("%.*f", digits, v)
end

function emit_macro(io::IO, name::String, value::String)
    safe = replace(value, "\\" => " ")
    println(io, "\\providecommand{\\$name}{$safe}")
    println(io, "\\renewcommand{\\$name}{$safe}")
end

function main()
    repo_root = pwd()
    out_file = joinpath(repo_root, "manuscript", "generated", "generated_metrics.tex")
    mkpath(dirname(out_file))

    report_manifest = read_json(joinpath(repo_root, "data", "outputs", "report_manifest.json"))

    open(out_file, "w") do io
        now_utc = Dates.format(Dates.now(Dates.UTC), dateformat"yyyy-mm-ddTHH:MM:SSZ")
        println(io, "% AUTO-GENERATED by scripts/export_manuscript_metrics.jl")
        println(io, "% DO NOT EDIT MANUALLY")
        println(io, "% Generated-UTC: $now_utc")
        println(io)

        if report_manifest !== nothing
            emit_macro(io, "GlobalDeff", fmt_num(get(report_manifest, "d_eff", nothing), digits=4))
            emit_macro(io, "GlobalConditionNum", fmt_num(get(report_manifest, "condition_num", nothing), digits=2))
            emit_macro(io, "GlobalSamples", string(get(report_manifest, "total_samples", "n/a")))
            emit_macro(io, "GlobalEntropy", fmt_num(get(report_manifest, "h_mean", nothing), digits=4))
        else
            emit_macro(io, "GlobalDeff", "n/a")
            emit_macro(io, "GlobalConditionNum", "n/a")
            emit_macro(io, "GlobalSamples", "n/a")
            emit_macro(io, "GlobalEntropy", "n/a")
        end

        for (campaign_name, slug, prefix) in CAMPAIGN_MAP
            s5_summary_path = joinpath(repo_root, "data", "outputs", "stage5_summary_$(slug).json")
            s5_summary = read_json(s5_summary_path)

            # Campaign D_eff currently resolves from report_manifest when campaign-specific report has just been generated.
            d_eff = nothing
            if report_manifest !== nothing
                if string(get(report_manifest, "campaign", "")) == campaign_name
                    d_eff = get(report_manifest, "d_eff", nothing)
                end
            end

            emit_macro(io, "$(prefix)Deff", fmt_num(d_eff, digits=4))

            if s5_summary === nothing
                emit_macro(io, "$(prefix)ClosestGamma", "n/a")
                emit_macro(io, "$(prefix)DReDGamma", "n/a")
                emit_macro(io, "$(prefix)HopfPeriodHours", "n/a")
                emit_macro(io, "$(prefix)StableRows", "n/a")
                emit_macro(io, "$(prefix)UnstableRows", "n/a")
                continue
            end

            emit_macro(io, "$(prefix)ClosestGamma", fmt_num(get(s5_summary, "closest_to_axis_gamma", nothing), digits=6))
            emit_macro(io, "$(prefix)DReDGamma", fmt_num(get(s5_summary, "dRe_dgamma_at_crossing", nothing), digits=4))
            emit_macro(io, "$(prefix)HopfPeriodHours", fmt_num(get(s5_summary, "hopf_period_Th", nothing), digits=2))
            emit_macro(io, "$(prefix)StableRows", string(get(s5_summary, "stable_rows", "n/a")))
            emit_macro(io, "$(prefix)UnstableRows", string(get(s5_summary, "unstable_rows", "n/a")))
        end
    end

    println("Wrote manuscript metrics macros: $(out_file)")
end

main()