using Printf
using DataFrames

include("scripts/DiagnosticsBaseline.jl")

using .DiagnosticsBaseline

"""
    regenerate_all_diagnostics(; data_dir="data", output_tex="drafts/sections/generated/diagnostics_generated.tex")

Recompute D_eff summary statistics from trajectory CSVs and export TeX macros.
"""
function regenerate_all_diagnostics(; data_dir="data", output_tex="drafts/sections/generated/diagnostics_generated.tex")
    raw_df, source_path = load_master_trajectory(data_dir)
    clean_df, _, dropped_rows, missing_cols = clean_diagnostics_frame(raw_df)

    if !isempty(missing_cols)
        error("Missing required diagnostics columns: $(join(missing_cols, ", "))")
    end

    if nrow(clean_df) == 0
        error("No usable diagnostics samples found in trajectory data under $(data_dir).")
    end

    summary = diagnostics_summary(clean_df; early_count=3024)
    macros = diagnostics_summary_macros(clean_df; early_count=3024)

    mkpath(dirname(output_tex))
    open(output_tex, "w") do f
        write(f, "% AUTO-GENERATED by regenerate_all_diagnostics()\n")
        write(f, "% DO NOT EDIT MANUALLY\n")
        for line in tex_provenance_comments(summary.samples, source_path)
            write(f, line * "\n")
        end
        write(f, "% Dropped-NonFinite-Rows: $(dropped_rows)\n\n")
        for k in sort(collect(keys(macros)))
            write(f, "\\providecommand{\\$(k)}{$(macros[k])}\n")
            write(f, "\\renewcommand{\\$(k)}{$(macros[k])}\n")
        end
    end

    println("✓ Wrote $(output_tex)")
    println("  Baseline: $(BASELINE_VERSION) from $(BASELINE_SOURCE)")
    println("  Samples: $(summary.samples), dropped non-finite rows: $(dropped_rows)")
    println("  D_eff: mean=$(round(summary.d_eff.mean, digits=2)), early=$(round(summary.d_eff.early, digits=2)), late=$(round(summary.d_eff.late, digits=2))")
    println("  F_W:   mean=$(round(summary.f_w.mean, digits=3)), early=$(round(summary.f_w.early, digits=3)), late=$(round(summary.f_w.late, digits=3))")
    println("  chi_N: mean=$(round(summary.chi_n.mean, digits=3)), early=$(round(summary.chi_n.early, digits=3)), late=$(round(summary.chi_n.late, digits=3))")
    println("  Include in manuscript preamble (optional): \\input{sections/generated/diagnostics_generated.tex}")
end

regenerate_all_diagnostics()
