module TexExporter

using DataFrames
using Printf

export export_table, export_parameters

function format_val(v; digits::Int=3)
    if v isa Number
        if !isfinite(Float64(v))
            return "nan"
        end
        return @sprintf("%.*f", digits, Float64(v))
    end
    return string(v)
end

"""
    export_table(df, output_path; caption, label, digits)

Write a compact booktabs LaTeX table from a DataFrame.
"""
function export_table(df::DataFrame, output_path::String; caption::String="", label::String="", digits::Int=3)
    mkpath(dirname(output_path))

    cols = String.(names(df))
    open(output_path, "w") do io
        write(io, "% AUTO-GENERATED by TexExporter.export_table\n")
        write(io, "\\begin{table}[t]\n")
        write(io, "\\centering\n")
        write(io, "\\begin{tabular}{" * join(fill("c", length(cols)), "") * "}\n")
        write(io, "\\toprule\n")
        write(io, join(cols, " & ") * " \\\\n")
        write(io, "\\midrule\n")
        for row in eachrow(df)
            vals = [format_val(row[c]; digits=digits) for c in names(df)]
            write(io, join(vals, " & ") * " \\\\n")
        end
        write(io, "\\bottomrule\n")
        write(io, "\\end{tabular}\n")
        if !isempty(caption)
            write(io, "\\caption{" * caption * "}\n")
        end
        if !isempty(label)
            write(io, "\\label{" * label * "}\n")
        end
        write(io, "\\end{table}\n")
    end
end

"""
    export_parameters(ws, output_path)

Emit basic workspace configuration macros for manuscript injection.
"""
function export_parameters(ws, output_path::String)
    mkpath(dirname(output_path))

    open(output_path, "w") do io
        write(io, "% AUTO-GENERATED by TexExporter.export_parameters\n")
        write(io, "\\providecommand{\\arcticGridN}{" * string(ws.N) * "}\n")
        write(io, "\\renewcommand{\\arcticGridN}{" * string(ws.N) * "}\n")
        write(io, "\\providecommand{\\arcticZZero}{" * @sprintf("%.3f", ws.z_0m) * "}\n")
        write(io, "\\renewcommand{\\arcticZZero}{" * @sprintf("%.3f", ws.z_0m) * "}\n")
        write(io, "\\providecommand{\\arcticZTop}{" * @sprintf("%.3f", ws.z_top) * "}\n")
        write(io, "\\renewcommand{\\arcticZTop}{" * @sprintf("%.3f", ws.z_top) * "}\n")
        write(io, "\\providecommand{\\arcticStretch}{" * @sprintf("%.3f", ws.alpha_stretch) * "}\n")
        write(io, "\\renewcommand{\\arcticStretch}{" * @sprintf("%.3f", ws.alpha_stretch) * "}\n")
    end
end

end # module
